### ISSUE TITLE
question: mod divisor require > 0 

### ISSUE THREAD

**Issue by kingofthebongo2008** [WaultFinance/WAULT#2]
Hello why the divisor for the mod function is not the same as for the div function ?
div function requires b > 0
mod requires b != 0

**Comment by kingofthebongo2008** [comment]
this is only for the wex, wault seems to be the same both for div and mod

**Comment by WaultFinance** [comment]
The mentioned function is from the external SafeMath library by OpenZeppelin. The reason why it differs in Wex and Wault is because different versions of the library are used.
You can find more information about OpenZeppelin contracts [here](https://github.com/OpenZeppelin/openzeppelin-contracts).
